export const JWT_ACCESS_TOKEN_EXPIRATION_TIME =
  'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME =
  'JWT_REFRESH_TOKEN_EXPIRATION_TIME';
export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_ACCESS_TOKEN_COOKIE_MAX_AGE =
  'JWT_ACCESS_TOKEN_COOKIE_MAX_AGE';
export const JWT_REFRESH_TOKEN_COOKIE_MAX_AGE =
  'JWT_REFRESH_TOKEN_COOKIE_MAX_AGE';
